### ISSUE TITLE
Allow invalid certificates

### ISSUE THREAD

**Issue by PurpleMyst** [aatxe/irc#230] opened 2021-03-04 18:50 UTC
As per the title, I'd enjoy it if there were an option to allow invalid certificates when connecting over TLS, as I believe this to be an use-case for connecting to a ZNC bouncer that has its own, self-signed, certificate, created by `znc --makecert` (or something of the like, I'm not sure that that's the right flag).

Currently, I get an error even if I convert the `znc.pem` into a `znc.der` and pass it in in the config.

**Comment by 8573** [comment] 2021-03-04 19:15
I don't know that I'd call self-signed certificates "invalid". I think it would be appropriate to have an option to accept any certificate with a fingerprint in a given list of fingerprints, so one would provide the fingerprint of one's self-signed certificate, just as often is done with certificate authentication to IRC services.

**Comment by dabukalam** [comment] 2021-05-27 23:15
I've run into this issue today as well, while trying to use https://github.com/nuxeh/url-bot-rs. Allowing self-signed certs somehow is def a good feature request.

**Comment by simnalamburt** [comment] 2021-11-14 17:20
Duplicate of https://github.com/aatxe/irc/issues/209

**Comment by simnalamburt** [comment] 2021-11-14 20:57
FYI, I've made a PR for this issue: https://github.com/aatxe/irc/pull/236

**Comment by ghost** [comment] 2022-02-19 06:26
Hey, 
I second this and in the meantime I've just switched to tracking @simnalamburt's upstream:

`irc = { git = "https://github.com/simnalamburt/irc.git", branch = "dangerously-accept-invalid-certs"  }`

https://github.com/clandestinenetworks/roobot/blob/master/src/main.rs#L15

and it seems to work just fine. thanks!

**Comment by quite** [comment] 2022-02-26 06:10
Closed by #236  it seems

**Closed as completed** 2022-03-01 20:24 UTC
